// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVkFuVDXBv7UJKmvIm6s2yhu4TUmH4ous',
    appId: '1:175469055056:web:43f5eb25bfabc0447a9555',
    messagingSenderId: '175469055056',
    projectId: 'flutter-web-restaurant',
    authDomain: 'flutter-web-restaurant.firebaseapp.com',
    storageBucket: 'flutter-web-restaurant.appspot.com',
    measurementId: 'G-89KM7W984N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfTNpU6eyA5aH3qzUTb-_5zs-Bini9SM',
    appId: '1:175469055056:android:1e6173d32ec273897a9555',
    messagingSenderId: '175469055056',
    projectId: 'flutter-web-restaurant',
    storageBucket: 'flutter-web-restaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrVBK7v9uE0Hu2qGhqK46uTRPageWe-M',
    appId: '1:175469055056:ios:dd7aff9f1a6373927a9555',
    messagingSenderId: '175469055056',
    projectId: 'flutter-web-restaurant',
    storageBucket: 'flutter-web-restaurant.appspot.com',
    iosBundleId: 'com.example.fundamentalBeginnerRestourant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYrVBK7v9uE0Hu2qGhqK46uTRPageWe-M',
    appId: '1:175469055056:ios:cb76028be930cbe07a9555',
    messagingSenderId: '175469055056',
    projectId: 'flutter-web-restaurant',
    storageBucket: 'flutter-web-restaurant.appspot.com',
    iosBundleId: 'com.example.fundamentalBeginnerRestourant.RunnerTests',
  );
}
